analytics: {}
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.062507
  lightness: 0.161545
  rhythmicContrast: 0.663463
  saturation: 0.925557
cta: {}
layout_spectrum: 0.15500228805467486
name: I want local food
opengraph: {}
purpose: []
typography_spectrum: 0.3552295414265245
